### PR TITLE
feat: reg. img upload not just dragdrop

### PR DESCRIPTION
**Pull request by bobmitch**
Adds file input button so mobile users can upload images too!
(or people who just prefer that interface too I guess)

### CODE REVIEW

**Comment by workaj** [comment]
do you have an image of what this looks like, or a site i can try it out on?

**Comment by bobmitch** [comment]
> do you have an image of what this looks like, or a site i can try it out on?

You are a user here: https://cmstest.bobmitch.com/admin

Find any [image upload page](https://cmstest.bobmitch.com/admin/images/show/) and you should see this new button to try out.

image

**Comment by bobmitch** [comment]
Just realized this undoes some stuff it shouldn't - brb fixing it.

**Comment by bobmitch** [comment]
Should be good to test / review now @workaj

**Review by workaj — APPROVED** [review]

**Pull request merged**
