### PR TITLE
feat: switch to tab with error if present

### PR DESCRIPTION
**Pull request by workaj**
see title - also done in a repeatable element friendly fashion

how to test:
checkout this pr, make sure your paganation is set to something over 100, save it
apply bobs broken commit https://github.com/HoltBosse/Alba/commit/32a4c7176ff70fb5321ecc7675d68dab56e885b3
try to save again, notice it properly switches to the tab with the error. observe no more warnings in the console about unfocusable elements.

### CODE REVIEW

**Comment by bobmitch** [comment]
It works! But... the way I was going to hit it (if I had the willpower like you do) would have been to use the invalid event:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/invalid_event

This way there's no inefficient looping / query selecting etc to get the element and it's containing tab, just a nice and clean event with the element delivered on a platter.

**Comment by workaj** [comment]
> It works! But... the way I was going to hit it (if I had the willpower like you do) would have been to use the invalid event:
> 
> https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/invalid_event
> 
> This way there's no inefficient looping / query selecting etc to get the element and it's containing tab, just a nice and clean event with the element delivered on a platter.

im aware of the invalid event. it is objectively worse for what the requirements are here, mainly because it can provide multiple triggers instead of one. you want just one trigger on page load to set that tab to active, else you have to do checking each time to make sure that there isnt already is-active tabs. additionally, the event is still just going to give you the invelid element, you will have to query up to find the tab content wrapper, and the tab header. also my solution, doesnt contain any looping. as for being "clean", no, its going to make the code about double the size, and probably even more querying since your always checking for is-active tabs.

**Comment by bobmitch** [comment]
FYI looks like the invalid event doesn't bubble, but it does appear to fire on both the element in question _and_ **the form** it's in - which might be good enough?

**Review by bobmitch — APPROVED** [review]
looks good

**Pull request merged**
