### PR TITLE
feat: adds console log as less obtrusive pprint_r.

### PR DESCRIPTION
**Pull request by anthonyisensee**
This may be bloat, but I think it could be helpful. Was useful at times when I was working on layout, especially because I didn't want whatever I was `CMS::pprint_r`ing vomited out into my layout.

What do you guys think @workaj  @bobmitch?

### CODE REVIEW

**Comment by workaj** [comment]
seems wasteful, and limiting. suggestion:
```php
public static function pprint_js($o, $mode="log") {
    	echo "<script>console.$mode(" . json_encode($o) . ");</script>";
}
```

**Comment by anthonyisensee** [comment]
Ooo, me likey. Will test it out when I get a chance and update pr.

**Comment by anthonyisensee** [comment]
@bobmitch we need you to be the tiebreaker between CMS::console_log() and CMS::pprint_js() for this.

**Comment by workaj** [comment]
or something better 🙃

**Comment by anthonyisensee** [comment]
Ah yes, a third option. xD

**Comment by anthonyisensee** [comment]
@workaj ready!

**Review by workaj — APPROVED** [review]
looks good

**Pull request merged**
