### PR TITLE
feat: add http error code in raise error function

### PR DESCRIPTION
**Pull request by workaj**
fixes https://github.com/HoltBosse/Alba/issues/209

see title

### CODE REVIEW

**Comment by bobmitch** [comment]
Should the function line be:

```php
public static function show_error($text, $http_code="500") {
```
and then you can do this:
```php
http_response_code($http_code);
``` 
on line 162?

**Comment by workaj** [comment]
🤷 was originally meant for gui only, but would work

**Comment by workaj** [comment]
resolved

**Review by bobmitch — APPROVED** [review]
looks good

**Pull request merged**
