### PR TITLE
Turnstile

### PR DESCRIPTION
**Pull request by bobmitch**

### CODE REVIEW

**Comment by bobmitch** [comment]
Please test first. (Add your site / get api keys using info here: https://staff.holtbosse.com/vault/812 )

**Comment by workaj** [comment]
beat me to it. ill look at this after lunch

**Comment by bobmitch** [comment]
> beat me to it. ill look at this after lunch

wasn't intending to do it - but the migration path from google was almost literally changing a url for server side and the js snippet for front end - so just did it while reading the docs

**Comment by workaj** [comment]
saving anything in general options currently appears to be broken - looking at this pr, i cant see anything that would break it

**Comment by workaj** [comment]
commit https://github.com/HoltBosse/Alba/commit/32a4c7176ff70fb5321ecc7675d68dab56e885b3 is to blame @bobmitch

**Comment by bobmitch** [comment]
> commit [32a4c71](https://github.com/HoltBosse/Alba/commit/32a4c7176ff70fb5321ecc7675d68dab56e885b3) is to blame @bobmitch

haven't tried to replicate yet (just got in the house) - but can't see _how_ that commit would break anything.

**Comment by workaj** [comment]
> > commit [32a4c71](https://github.com/HoltBosse/Alba/commit/32a4c7176ff70fb5321ecc7675d68dab56e885b3) is to blame @bobmitch
> 
> haven't tried to replicate yet (just got in the house) - but can't see _how_ that commit would break anything.

if i was to guess its due to the change there starting a cascade down to where the blocking of setting stuff is

**Comment by bobmitch** [comment]
Figured out the issue:

- Default pagination set to 200
- Default max for 'number' text field is 100 if no max is set (i)
- When you try to save config settings the browser sanity check is flagging this field (since 200 > 100) but,,,
- This field is in another form 'tab' and is hidden (ii)

(i)  This is maybe dumb, but old me maybe thought that percentages were a good default.... realistically, this should probably be MAXINT or just nothing at all maybe...

(ii)  This is a problem - tangentially related to https://github.com/HoltBosse/Alba/issues/139 - possible to handle via JS, so I should probably do that.... 

For now - think I will change the default max for number/text fields to just be empty instead of 100 - maybe same for min.  https://github.com/HoltBosse/Alba/commit/32a4c7176ff70fb5321ecc7675d68dab56e885b3#diff-08f79b533f66ad9a10b18d3910d74e69546e055affecd1d2c7a5ec0d1acd2a79R97

What say you @workaj

**Comment by workaj** [comment]
> Figured out the issue:
> 
> * Default pagination set to 200
> * Default max for 'number' text field is 100 if no max is set (i)
> * When you try to save config settings the browser sanity check is flagging this field (since 200 > 100) but,,,
> * This field is in another form 'tab' and is hidden (ii)
> 
> (i) This is maybe dumb, but old me maybe thought that percentages were a good default.... realistically, this should probably be MAXINT or just nothing at all maybe...
> 
> (ii) This is a problem - tangentially related to #139 - possible to handle via JS, so I should probably do that....
> 
> For now - think I will change the default max for number/text fields to just be empty instead of 100 - maybe same for min. [32a4c71#diff-08f79b533f66ad9a10b18d3910d74e69546e055affecd1d2c7a5ec0d1acd2a79R97](https://github.com/HoltBosse/Alba/commit/32a4c7176ff70fb5321ecc7675d68dab56e885b3#diff-08f79b533f66ad9a10b18d3910d74e69546e055affecd1d2c7a5ec0d1acd2a79R97)
> 
> What say you @workaj

(i) yeah, a limit of 100 is not good, additionally this breaks me being lazing and setting session timeout very high.

(ii) perhaps when the fix is made (more than just js) the pane the user is on can be respected rather than reset to the first one

**Comment by workaj** [comment]
tested, last commit does fix the settings issue. going to attempt to try turnstile now

**Review by workaj — APPROVED** [review]
works

**Pull request merged**
