### PR TITLE
multifeatures

### PR DESCRIPTION
**Pull request by workaj**
includes a few features

* [x] loading a form from obj in addition to from a file
* [x] autoloading of core controllers
* [x] multiselect
* [x] default 404

### CODE REVIEW

**Comment by workaj** [comment]
test code for form obj loading

```php
<?php
defined('CMSPATH') or die; // prevent unauthorized access

echo "no file form: <br>";
$nofileform = new Form();
CMS::pprint_r($nofileform);

echo "broken string form: <br>";
$brokenstringform = new Form("");
CMS::pprint_r($brokenstringform);

echo "obj passed form: <br>";
$json = file_get_contents(CMSPATH . "/testform.json");
$obj = json_decode($json);
$objform = new Form($obj);
CMS::pprint_r($objform);
```

**Comment by workaj** [comment]
test auto core controller loading by creating folder dev_obj_form in core/controllers/ and creating file controller.php with the content listed above

**Comment by workaj** [comment]
image
default 404 page

**Comment by workaj** [comment]
to test multiselect, use the following json
```json
{
	"id":"wp_demo",
	"fields":[
        {
			"type":"Select",
            "id":"brand",
            "name":"brand",
            "required":false,
            "label":"brand",
            "filter": "STRING",
            "default": "",
            "select_options": [
				{"value": "6", "text": "brand_M"},
                {"value": "7", "text": "brand_K"},
                {"value": "5", "text": "brand_W"},
                {"value": "8", "text": "brand_A"}
			]
        },
        {
			"type":"Select",
            "id":"category",
            "name":"category",
            "required":false,
            "label":"category",
            "filter": "STRING",
            "default": "",
            "select_options": [
				{"value": "OPTION", "text": "OPTION", "UpdateSelect": {
                    "id":"subcategory",
                    "select_options": [
                        {"value": "categoryOPTION1", "text": "categoryOPTION1" },
                        {"value": "categoryOPTION2", "text": "categoryOPTION2" }
                    ]
                }},
                {"value": "DEMO", "text": "DEMO", "UpdateSelect": {
                    "id":"subcategory",
                    "select_options": [
                        {"value": "categoryDEMO1", "text": "categoryDEMO1" },
                        {"value": "categoryDEMO2", "text": "categoryDEMO2" }
                    ]
                }}
			]
        },
        {
			"type":"Select",
            "id":"subcategory",
            "name":"subcategory",
            "required":false,
            "label":"subcategory",
            "filter": "STRING",
            "default": "",
            "select_options": [
				{"value": "%", "text": "ALL"}
			]
        }
	]
}
```

**Review by bobmitch — APPROVED** [review]
awesome stuff

**Pull request merged**
