### PR TITLE
init: autopub

### PR DESCRIPTION
**Pull request by bobmitch**

### CODE REVIEW

**Comment by workaj** [comment]
image
not a searchable state

**Comment by workaj** [comment]
image
pretty confusing when you try and click the toggle, and it does nothing (im assuming since the content is already over

**Comment by workaj** [comment]
probably unrelated to this pr, but duplicate functionality seems to be broken in general

**Comment by workaj** [comment]
i can set a pending article to a page in the control settup, lets talk about this - what it should do

**Comment by workaj** [comment]
also need to be able to reset the end date

**Comment by bobmitch** [comment]
> also need to be able to reset the end date

native pickers all have a clear option - you think we need to have an explicit clear grouped with the input field as well? 
image

**Comment by bobmitch** [comment]
> image not a searchable state
> 
> also should only be one on content types where its enabled

https://github.com/HoltBosse/Alba/commit/a84db17ad97fec007c9f5a2cbfdc7be60f21f7f6

**Comment by bobmitch** [comment]
> i can set a pending article to a page in the control settup, lets talk about this - what it should do

think it needs to be pickable - might need to append (pending) or something to the title in the picker/select. need chat to discuss for sure.

**Pull request closed without merging**
